FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package.json package-lock.json* ./
RUN npm install --omit=dev --no-audit --no-fund
COPY .next ./.next
COPY public ./public
COPY next.config.mjs ./
EXPOSE 3000
CMD ["npm", "start"]
