module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.ts$': ['ts-jest', { tsconfig: 'tsconfig.json' }],
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.spec.ts',
    '!src/**/*.entity.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.module.ts',
    '!src/main.ts',
    '!src/database/**',
    '!src/**/*.guard.ts',
    '!src/**/*.strategy.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.decorator.ts',
    '!src/**/*.filter.ts',
    '!src/**/*.interceptor.ts',
    '!src/**/*.middleware.ts',
    '!src/**/*.pipe.ts',
    '!src/**/*.controller.ts',
    '!src/**/*.cron.ts',
    '!src/**/pdf.ts',
    '!src/**/interfaces/**',
    '!src/**/providers/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'text-summary', 'html', 'json-summary'],
  verbose: false,
};
