/**
 * PROCHECK Solutions default course catalog.
 * Mirrors frontend/src/lib/courses.ts and is inserted on an empty courses
 * table by CoursesService.seedIfEmpty(). Editing here does NOT re-run on an
 * already-populated table — use admin CRUD to change existing rows.
 */
export interface CourseSeed {
  code: string;
  title: string;
  hours: number;
  price: number;
  image: string;
  industry: 'quimica' | 'metalmecanica' | 'mineria' | 'construccion' | 'general';
  tier: 'basico' | 'complementario';
  description?: string;
}

export const COURSE_SEED: CourseSeed[] = [
  // Básicos (NOM)
  {
    code: 'NOM-009',
    title: 'NOM-009-STPS Trabajos en altura',
    hours: 6,
    price: 850,
    image: '/images/courses/NOM-009.jpg',
    industry: 'construccion',
    tier: 'basico',
    description: 'Prevención de caídas y sistemas personales de detención.',
  },
  {
    code: 'NOM-017',
    title: 'NOM-017-STPS Equipo de protección personal',
    hours: 4,
    price: 650,
    image: '/images/courses/NOM-017.jpg',
    industry: 'general',
    tier: 'basico',
    description: 'Selección, uso y mantenimiento del EPP.',
  },
  {
    code: 'NOM-002',
    title: 'NOM-002-STPS Prevención y protección contra incendios',
    hours: 5,
    price: 750,
    image: '/images/courses/NOM-002.jpg',
    industry: 'general',
    tier: 'basico',
  },
  {
    code: 'NOM-019',
    title: 'NOM-019-STPS Comisiones de Seguridad e Higiene',
    hours: 4,
    price: 600,
    image: '/images/courses/NOM-019.jpg',
    industry: 'general',
    tier: 'basico',
  },
  {
    code: 'NOM-036',
    title: 'NOM-036-STPS Ergonomía en el trabajo',
    hours: 4,
    price: 620,
    image: '/images/courses/NOM-036.jpg',
    industry: 'metalmecanica',
    tier: 'basico',
  },
  {
    code: 'NOM-004',
    title: 'NOM-004-STPS Sistemas y dispositivos de seguridad en maquinaria',
    hours: 6,
    price: 780,
    image: '/images/courses/NOM-004.jpg',
    industry: 'metalmecanica',
    tier: 'basico',
  },
  {
    code: 'NOM-001',
    title: 'NOM-001-STPS Edificios, locales e instalaciones',
    hours: 4,
    price: 590,
    image: '/images/courses/NOM-001.jpg',
    industry: 'general',
    tier: 'basico',
  },
  {
    code: 'NOM-006',
    title: 'NOM-006-STPS Manejo y almacenamiento de materiales',
    hours: 5,
    price: 690,
    image: '/images/courses/NOM-006.jpg',
    industry: 'construccion',
    tier: 'basico',
  },
  {
    code: 'NOM-026',
    title: 'NOM-026-STPS Colores y señales de seguridad',
    hours: 3,
    price: 480,
    image: '/images/courses/NOM-026.jpg',
    industry: 'general',
    tier: 'basico',
  },
  {
    code: 'NOM-027',
    title: 'NOM-027-STPS Actividades de soldadura y corte',
    hours: 6,
    price: 820,
    image: '/images/courses/NOM-027.jpg',
    industry: 'metalmecanica',
    tier: 'basico',
  },
  {
    code: 'NOM-029',
    title: 'NOM-029-STPS Mantenimiento de instalaciones eléctricas',
    hours: 6,
    price: 810,
    image: '/images/courses/NOM-029.jpg',
    industry: 'general',
    tier: 'basico',
  },
  {
    code: 'NOM-030',
    title: 'NOM-030-STPS Servicios preventivos de seguridad y salud',
    hours: 4,
    price: 640,
    image: '/images/courses/NOM-030.jpg',
    industry: 'general',
    tier: 'basico',
  },
  {
    code: 'NOM-005',
    title: 'NOM-005-STPS Manejo de sustancias químicas peligrosas',
    hours: 6,
    price: 890,
    image: '/images/courses/NOM-005.jpg',
    industry: 'quimica',
    tier: 'basico',
  },
  {
    code: 'NOM-010',
    title: 'NOM-010-STPS Agentes químicos contaminantes',
    hours: 5,
    price: 760,
    image: '/images/courses/NOM-010.jpg',
    industry: 'quimica',
    tier: 'basico',
  },
  {
    code: 'NOM-023',
    title: 'NOM-023-STPS Trabajos en minas',
    hours: 8,
    price: 990,
    image: '/images/courses/NOM-023.jpg',
    industry: 'mineria',
    tier: 'basico',
  },
  {
    code: 'NOM-031',
    title: 'NOM-031-STPS Seguridad en la industria de la construcción',
    hours: 6,
    price: 830,
    image: '/images/courses/NOM-031.jpg',
    industry: 'construccion',
    tier: 'basico',
  },
  // Complementarios
  {
    code: 'LOTO-101',
    title: 'LOTO-101 Bloqueo y etiquetado (Lockout/Tagout)',
    hours: 4,
    price: 630,
    image: '/images/courses/LOTO-101.jpg',
    industry: 'metalmecanica',
    tier: 'complementario',
  },
  {
    code: 'EX-101',
    title: 'EX-101 Excavaciones y trabajos subterráneos',
    hours: 4,
    price: 640,
    image: '/images/courses/EX-101.jpg',
    industry: 'construccion',
    tier: 'complementario',
  },
  {
    code: 'EXT-101',
    title: 'EXT-101 Uso y manejo de extintores',
    hours: 2,
    price: 450,
    image: '/images/courses/EXT-101.jpg',
    industry: 'general',
    tier: 'complementario',
  },
  {
    code: 'PA-101',
    title: 'PA-101 Primeros auxilios básicos',
    hours: 3,
    price: 520,
    image: '/images/courses/PA-101.jpg',
    industry: 'general',
    tier: 'complementario',
  },
  {
    code: 'EC-101',
    title: 'EC-101 Espacios confinados',
    hours: 5,
    price: 720,
    image: '/images/courses/EC-101.jpg',
    industry: 'quimica',
    tier: 'complementario',
  },
  {
    code: 'MM-101',
    title: 'MM-101 Manejo manual de cargas',
    hours: 3,
    price: 490,
    image: '/images/courses/MM-101.jpg',
    industry: 'construccion',
    tier: 'complementario',
  },
  {
    code: 'IZ-101',
    title: 'IZ-101 Izajes y maniobras con grúa',
    hours: 6,
    price: 860,
    image: '/images/courses/IZ-101.jpg',
    industry: 'construccion',
    tier: 'complementario',
  },
  {
    code: 'MP-101',
    title: 'MP-101 Manejo de montacargas',
    hours: 5,
    price: 700,
    image: '/images/courses/MP-101.jpg',
    industry: 'metalmecanica',
    tier: 'complementario',
  },
];
